In [5]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver import ActionChains
import mysql.connector 

df_ap = pd.read_csv('df_AP.csv')
df_ap

,APSRTC_links,APSRTC_routes
0,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada
1,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Hyderabad
2,https://www.redbus.in/bus-tickets/kakinada-to-...,Kakinada to Visakhapatnam
3,https://www.redbus.in/bus-tickets/chittoor-and...,Chittoor (Andhra Pradesh) to Bangalore
4,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Tirupati
5,https://www.redbus.in/bus-tickets/tirupathi-to...,Tirupati to Bangalore
6,https://www.redbus.in/bus-tickets/kadapa-to-ba...,Kadapa to Bangalore
7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Ongole
8,https://www.redbus.in/bus-tickets/ananthapur-t...,Anantapur (andhra pradesh) to Bangalore
9,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kadapa
10,https://www.redbus.in/bus-tickets/ongole-to-hy...,Ongole to Hyderabad
11,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Chittoor (Andhra Pradesh)
12,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Anantapur (andhra pradesh)
13,https://www.redbus.in/bus-tickets/visakhapatna...,Visakhapatnam to Kakinada
14,https://www.redbus.in/bus-tickets/kadiri-to-ba...,Kadiri to Bangalore
15,https://www.redbus.in/bus-tickets/vinukonda-to...,Vinukonda to Hyderabad
16,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kadiri
17,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Narasaraopet
18,https://www.redbus.in/bus-tickets/madanapalli-...,Madanapalli to Bangalore
19,https://www.redbus.in/bus-tickets/narsaraopet-...,Narasaraopet to Hyderabad
20,https://www.redbus.in/bus-tickets/rajahmundry-...,Rajahmundry to Visakhapatnam
21,https://www.redbus.in/bus-tickets/eluru-to-hyd...,Eluru to Hyderabad
22,https://www.redbus.in/bus-tickets/chennai-to-t...,Chennai to Tirupati
23,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Madanapalli
24,https://www.redbus.in/bus-tickets/guntur-to-hy...,Guntur (Andhra Pradesh) to Hyderabad
25,https://www.redbus.in/bus-tickets/rayachoti-to...,Rayachoti to Bangalore
26,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kurnool
27,https://www.redbus.in/bus-tickets/tirupathi-to...,Tirupati to Chennai
28,https://www.redbus.in/bus-tickets/visakhapatna...,Visakhapatnam to Vijayawada
29,https://www.redbus.in/bus-tickets/rajahmundry-...,Rajahmundry to Vijayawada
30,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Guntur (Andhra Pradesh)
31,https://www.redbus.in/bus-tickets/macherla-to-...,Macherla (andhra pradesh) to Hyderabad
32,https://www.redbus.in/bus-tickets/nandyala-to-...,Nandyal to Hyderabad
33,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Eluru
34,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Rayachoti
35,https://www.redbus.in/bus-tickets/kurnool-to-h...,Kurnool to Hyderabad
36,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vinukonda
37,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Visakhapatnam
38,https://www.redbus.in/bus-tickets/kurnool-to-b...,Kurnool to Bangalore
39,https://www.redbus.in/bus-tickets/rajahmundry-...,Rajahmundry to Hyderabad
40,https://www.redbus.in/bus-tickets/amalapuram-t...,Amalapuram to Visakhapatnam
41,https://www.redbus.in/bus-tickets/kurnool-to-v...,Kurnool to Vijayawada
42,https://www.redbus.in/bus-tickets/visakhapatna...,Visakhapatnam to Rajahmundry
43,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Macherla (andhra pradesh)
44,https://www.redbus.in/bus-tickets/nellore-to-b...,Nellore to Bangalore
45,https://www.redbus.in/bus-tickets/tadipatri-to...,Tadipatri to Bangalore
46,https://www.redbus.in/bus-tickets/kakinada-to-...,Kakinada to Vijayawada
47,https://www.redbus.in/bus-tickets/visakhapatna...,Visakhapatnam to Amalapuram
48,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Markapuram
49,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal

In [13]:
# AP(ANDRA PRADESH)

driver = webdriver.Chrome()
driver.maximize_window()
apsrtc_bus_name = []
apsrtc_bus_type = []
apsrtc_departing_time = []
apsrtc_duration = []
apsrtc_reaching_time = []
apsrtc_star_rating = []
apsrtc_price = []
apsrtc_route_names = []
apsrtc_route_link = []
apsrtc_seat = []
for i , r in df_ap.iterrows():
    link = r['APSRTC_links'] # ,
    routes = r['APSRTC_routes']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            apsrtc_bus_name.append(Bus_name.text)
            apsrtc_bus_type.append(Bus_type.text)
            apsrtc_departing_time.append(Departing_time.text)
            apsrtc_duration.append(Duration.text)
            apsrtc_reaching_time.append(Reaching_time.text)
            apsrtc_price.append(price.text)
            apsrtc_star_rating.append(star_rating)
            apsrtc_route_link.append(link)
            apsrtc_route_names.append(routes)    
            apsrtc_seat.append(seat)

In [17]:
# print(apsrtc_seat)
# print(len(apsrtc_bus_name))
# print(len(apsrtc_bus_type))
# print(len(apsrtc_departing_time))
# print(len(apsrtc_duration))
# print(len(apsrtc_price))
# print(len(apsrtc_star_rating))
# print(len(apsrtc_reaching_time))
# print(len(apsrtc_route_names))
# print(len(apsrtc_route_link))

In [20]:
data1 = {'route_name':apsrtc_route_names,'route_link':apsrtc_route_link,'busname':apsrtc_bus_name,
         'bustype':apsrtc_bus_type,'departing_time':apsrtc_departing_time,'duration':apsrtc_duration,
         'reaching_time':apsrtc_reaching_time,'star_rating':apsrtc_star_rating,'price':apsrtc_price,
         'seats_available':apsrtc_seat}
df_state_1 = pd.DataFrame(data1)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\apsrtc_busdetails.csv'
df_state_1.to_csv(path,index=False)

In [22]:
df_buses_1 = pd.read_csv('apsrtc_busdetails.csv')
df_buses_1

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3859,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),15:15,06h 10m,21:25,3.1,INR 633,37 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3356,NIGHT RIDER (SEATER CUM SLEEPER),15:45,07h 00m,22:45,3.7,INR 595,20 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3546,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),16:15,06h 15m,22:30,3.7,INR 633,27 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3500,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:20,08h 25m,00:45,3.5,INR 436,20 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3376,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:45,06h 30m,23:15,4.8,INR 436,31 Seats available
...,...,...,...,...,...,...,...,...,...,...
4216,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,SREE LEKYAA TRAVELS,NON A/C Sleeper (2+1),21:40,05h 50m,03:30,3.8,950,14 Seats available
4217,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,SREE LEKYAA TRAVELS,A/C Sleeper (2+1),21:30,06h 05m,03:35,3.8,807,26 Seats available
4218,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,AR & BCVR Travels,NON A/C Sleeper (2+1),21:15,06h 15m,03:30,3.8,INR 799,24 Seats available
4219,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,True Bus,Volvo Multi Axle A/C Sleeper I-Shift B11R (2+1),22:00,05h 30m,03:30,2.9,INR 3000,36 Seats available
4220,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,True Bus,Volvo Multi Axle A/C Sleeper I-Shift B11R (2+1),22:00,06h 00m,04:00,2.9,INR 1400,36 Seats available

In [77]:
df_telu = pd.read_csv('df_telu.csv')
df_telu

,TSRTC_LINKS,TSRTC_routes
0,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad
1,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada
2,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Khammam
3,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Srisailam
4,https://www.redbus.in/bus-tickets/karimnagar-t...,Karimnagar to Hyderabad
5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Adilabad
6,https://www.redbus.in/bus-tickets/kothagudem-t...,Kothagudem to Hyderabad
7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Mancherial
8,https://www.redbus.in/bus-tickets/guntur-to-hy...,Guntur (Andhra Pradesh) to Hyderabad
9,https://www.redbus.in/bus-tickets/godavarikhan...,Godavarikhani to Hyderabad
10,https://www.redbus.in/bus-tickets/kodad-to-hyd...,Kodad to Hyderabad
11,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Ongole
12,https://www.redbus.in/bus-tickets/jagityal-to-...,Jagityal to Hyderabad
13,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nirmal
14,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Guntur (Andhra Pradesh)
15,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Karimnagar
16,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kothagudem
17,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Bhadrachalam
18,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Sathupally
19,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Warangal
20,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Tirupati
21,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Anantapur (andhra pradesh)
22,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Armoor
23,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Godavarikhani
24,https://www.redbus.in/bus-tickets/peddapalli-t...,Peddapalli (Telangana) to Hyderabad
25,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad

In [78]:
# telugu

driver = webdriver.Chrome()
driver.maximize_window()
telu_bus_name = []
telu_bus_type = []
telu_departing_time = []
telu_duration = []
telu_reaching_time = []
telu_star_rating = []
telu_price = []
telu_route_names = []
telu_route_link = []
telu_seat = []

for i , r in df_telu.iterrows():
    link = r['TSRTC_LINKS'] # ,
    routes = r['TSRTC_routes']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            telu_bus_name.append(Bus_name.text)
            telu_bus_type.append(Bus_type.text)
            telu_departing_time.append(Departing_time.text)
            telu_duration.append(Duration.text)
            telu_reaching_time.append(Reaching_time.text)
            telu_price.append(price.text)
            telu_star_rating.append(star_rating)
            telu_route_link.append(link)
            telu_route_names.append(routes)    
            telu_seat.append(seat)

In [80]:
data2 = {'route_name':telu_route_names,'route_link':telu_route_link,'busname':telu_bus_name,
         'bustype':telu_bus_type,'departing_time':telu_departing_time,'duration':telu_duration,
         'reaching_time':telu_reaching_time,'star_rating':telu_star_rating,'price':telu_price,
         'seats_available':telu_seat}
df_state_2 = pd.DataFrame(data2)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\telubusdetails.csv'
df_state_2.to_csv(path,index=False)

In [81]:
df_buses_2 = pd.read_csv('telubusdetails.csv')
df_buses_2

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...,TGSRTC - 8653,RAJADHANI AC (CONVERTED METRO LUXURY),03:00,04h 00m,07:00,4.5,INR 389,6 Seats available
1,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...,TGSRTC - 8631,RAJADHANI AC (CONVERTED METRO LUXURY),03:30,04h 00m,07:30,3.6,INR 389,16 Seats available
2,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...,TGSRTC - 8688,Rajdhani (AC Semi Sleeper 2+2),04:00,03h 20m,07:20,4.0,INR 389,7 Seats available
3,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...,TGSRTC - 8694,Rajdhani (AC Semi Sleeper 2+2),05:00,03h 20m,08:20,3.3,INR 389,3 Seats available
4,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...,TGSRTC - 1321,LAHARI A/C SLEEPER CUM SEATER,05:40,03h 40m,09:20,3.7,INR 389,13 Seats available
...,...,...,...,...,...,...,...,...,...,...
2105,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...,KVR Tours and Travels,A/C Sleeper (2+1),21:30,04h 30m,02:00,2.7,INR 3000,34 Seats available
2106,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...,VLR Tours and Travels,Volvo Multi-Axle A/C Sleeper (2+1),22:00,01h 00m,23:00,0.0,INR 2000,36 Seats available
2107,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...,VLR Tours and Travels,Volvo Multi-Axle A/C Sleeper (2+1),22:00,01h 00m,23:00,0.0,INR 2000,36 Seats available
2108,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...,VLR Tours and Travels,Volvo Multi-Axle A/C Sleeper (2+1),22:00,01h 00m,23:00,0.0,INR 2000,36 Seats available
2109,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...,Morning Star Travels,A/C Sleeper (2+1),22:30,04h 00m,02:30,2.7,INR 990,27 Seats available

In [28]:
df_k = pd.read_csv('df_k.csv')
df_k

,kadamba_link,kadamba_route
0,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
1,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune
2,https://www.redbus.in/bus-tickets/mumbai-to-goa,Mumbai to Goa
3,https://www.redbus.in/bus-tickets/goa-to-mumbai,Goa to Mumbai
4,https://www.redbus.in/bus-tickets/belagavi-to-goa,Belagavi to Goa
5,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Goa
6,https://www.redbus.in/bus-tickets/goa-to-banga...,Goa to Bangalore
7,https://www.redbus.in/bus-tickets/pandharpur-t...,Pandharpur to Goa
8,https://www.redbus.in/bus-tickets/goa-to-belagavi,Goa to Belagavi
9,https://www.redbus.in/bus-tickets/goa-to-kolha...,Goa to Kolhapur(Maharashtra)
10,https://www.redbus.in/bus-tickets/solapur-to-goa,Solapur to Goa
11,https://www.redbus.in/bus-tickets/goa-to-pandh...,Goa to Pandharpur
12,https://www.redbus.in/bus-tickets/goa-to-solapur,Goa to Solapur
13,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Goa Airport
14,https://www.redbus.in/bus-tickets/goa-to-sangola,Goa to Sangola (Solapur)
15,https://www.redbus.in/bus-tickets/sangola-to-goa,Sangola (Solapur) to Goa
16,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Mopa Airport
17,https://www.redbus.in/bus-tickets/goa-airport-...,Goa Airport to Calangute (goa)
18,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Calangute (goa)
19,https://www.redbus.in/bus-tickets/shimoga-to-goa,Shivamogga to Goa
20,https://www.redbus.in/bus-tickets/marcel-to-be...,Marcel to Belagavi
21,https://www.redbus.in/bus-tickets/ponda-to-bel...,Ponda to Belagavi
22,https://www.redbus.in/bus-tickets/belagavi-to-...,Belagavi to Marcel
23,https://www.redbus.in/bus-tickets/belagavi-to-...,Belagavi to Ponda
24,https://www.redbus.in/bus-tickets/panaji-to-go...,Panaji to Goa Airport
25,https://www.redbus.in/bus-tickets/goa-to-sangli,Goa to Sangli
26,https://www.redbus.in/bus-tickets/goa-to-mopa-...,Goa to Mopa Airport
27,https://www.redbus.in/bus-tickets/goa-to-miraj,Goa to Miraj
28,https://www.redbus.in/bus-tickets/margoa-to-mo...,Margao to Mopa Airport
29,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Goa
30,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Margao
31,https://www.redbus.in/bus-tickets/goa-airport-...,Goa Airport to Panaji
32,https://www.redbus.in/bus-tickets/shirdi-to-goa,Shirdi to Goa
33,https://www.redbus.in/bus-tickets/goa-to-shimoga,Goa to Shivamogga
34,https://www.redbus.in/bus-tickets/goa-to-satara,Goa to Satara
35,https://www.redbus.in/bus-tickets/panaji-to-mo...,Panaji to Mopa Airport
36,https://www.redbus.in/bus-tickets/saquelim-to-...,Saquelim to Belagavi
37,https://www.redbus.in/bus-tickets/goa-to-goa-a...,Goa to Goa Airport
38,https://www.redbus.in/bus-tickets/goa-to-shirdi,Goa to Shirdi
39,https://www.redbus.in/bus-tickets/goa-airport-...,Goa Airport to Goa
40,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Goa
41,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Panaji
42,https://www.redbus.in/bus-tickets/goa-to-calan...,Goa to Calangute (goa)
43,https://www.redbus.in/bus-tickets/belagavi-to-...,Belagavi to Saquelim
44,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Panaji

In [29]:
# kadamba

driver = webdriver.Chrome()
driver.maximize_window()
k_bus_name = []
k_bus_type = []
k_departing_time = []
k_duration = []
k_reaching_time = []
k_star_rating = []
k_price = []
k_route_names = []
k_route_link = []
k_seat = []
for i , r in df_k.iterrows():
    link = r['kadamba_link'] # ,
    routes = r['kadamba_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            k_bus_name.append(Bus_name.text)
            k_bus_type.append(Bus_type.text)
            k_departing_time.append(Departing_time.text)
            k_duration.append(Duration.text)
            k_reaching_time.append(Reaching_time.text)
            k_price.append(price.text)
            k_star_rating.append(star_rating)
            k_route_link.append(link)
            k_route_names.append(routes)    
            k_seat.append(seat)

In [30]:
data3 = {'route_name':k_route_names,'route_link':k_route_link,'busname':k_bus_name,
         'bustype':k_bus_type,'departing_time':k_departing_time,'duration':k_duration,
         'reaching_time':k_reaching_time,'star_rating':k_star_rating,'price':k_price,
         'seats_available':k_seat}
df_state_3 = pd.DataFrame(data3)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\kadamba_busdetails.csv'
df_state_3.to_csv(path,index=False)

In [31]:
df_buses_3 = pd.read_csv('kadamba_busdetails.csv')
df_buses_3

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune,Amrutyog Travels,A/C Sleeper (2+1),20:00,11h 22m,07:22,4.2,INR 1777,13 Seats available
1,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune,Ashray Travels,Bharat Benz A/C Sleeper (2+1),22:30,11h 30m,10:00,4.4,INR 1990,9 Seats available
2,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune,Ashray Grand,Volvo Multi-Axle A/C Sleeper (2+1),22:00,11h 30m,09:30,4.1,INR 2080,11 Seats available
3,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune,IntrCity SmartBus,AC Sleeper (2+1),19:00,10h 30m,05:30,4.2,INR 1760,7 Seats available
4,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),20:30,10h 15m,06:45,4.6,INR 1642,8 Seats available
...,...,...,...,...,...,...,...,...,...,...
363,Panaji to Mopa Airport,https://www.redbus.in/bus-tickets/panaji-to-mo...,Kadamba Transport Corporation Limited (KTCL) -...,A/C Seater (2+3),15:55,01h 05m,17:00,2.3,INR 200,48 Seats available
364,Goa to Shirdi,https://www.redbus.in/bus-tickets/goa-to-shirdi,Humsafar Travels,Bharat Benz A/C Sleeper (2+1),19:00,16h 00m,11:00,2.3,INR 2050,7 Seats available
365,Goa to Shirdi,https://www.redbus.in/bus-tickets/goa-to-shirdi,Hans Travels (I) Private Limited,A/C Sleeper (2+1),16:15,13h 00m,05:15,1.6,INR 1700,2 Seats available
366,Mopa Airport to Panaji,https://www.redbus.in/bus-tickets/mopa-airport...,Kadamba Transport Corporation Limited (KTCL) -...,A/C Seater (2+3),16:00,00h 55m,16:55,3.6,INR 200,45 Seats available
367,Belagavi to Saquelim,https://www.redbus.in/bus-tickets/belagavi-to-...,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,16:00,02h 15m,18:15,3.6,INR 140,2 Seats available

In [32]:
df_SB = pd.read_csv('df_SB.csv')
df_SB

,SB_link,SB_route
0,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata
1,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Burdwan
2,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Durgapur (West Bengal)
3,https://www.redbus.in/bus-tickets/haldia-to-ko...,Haldia to Kolkata
4,https://www.redbus.in/bus-tickets/kolkata-to-h...,Kolkata to Haldia
5,https://www.redbus.in/bus-tickets/midnapore-to...,Midnapore to Kolkata
6,https://www.redbus.in/bus-tickets/kolkata-to-a...,Kolkata to Arambagh (West Bengal)
7,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha
8,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata
9,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Bankura
10,https://www.redbus.in/bus-tickets/kolkata-to-a...,Kolkata to Asansol (West Bengal)
11,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Midnapore
12,https://www.redbus.in/bus-tickets/jhargram-to-...,Jhargram to Kolkata
13,https://www.redbus.in/bus-tickets/kolkata-to-c...,Kolkata to Contai (Kanthi)
14,https://www.redbus.in/bus-tickets/kolkata-to-n...,Kolkata to Nimtouri
15,https://www.redbus.in/bus-tickets/digha-to-dur...,Digha to Durgapur (West Bengal)
16,https://www.redbus.in/bus-tickets/kolkata-to-n...,Kolkata to Nandakumar (west bengal)
17,https://www.redbus.in/bus-tickets/kirnahar-wes...,Kirnahar (West Bengal) to Kolkata
18,https://www.redbus.in/bus-tickets/kolkata-to-k...,Kolkata to Kolaghat
19,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mecheda (West Bengal)
20,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Barasat (West Bengal)
21,https://www.redbus.in/bus-tickets/kolkata-to-c...,Kolkata to Chandipur (West Bengal)
22,https://www.redbus.in/bus-tickets/midnapore-to...,Midnapore to Barasat (West Bengal)
23,https://www.redbus.in/bus-tickets/berhampore-t...,Berhampore (West Bengal) to Durgapur (West Ben...
24,https://www.redbus.in/bus-tickets/kolkata-to-suri,Kolkata to Suri
25,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Digha
26,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Berhampore (West Ben...
27,https://www.redbus.in/bus-tickets/purulia-to-d...,Purulia to Durgapur (West Bengal)
28,https://www.redbus.in/bus-tickets/digha-to-bar...,Digha to Barasat (West Bengal)
29,https://www.redbus.in/bus-tickets/kolkata-to-h...,Kolkata to Heria
30,https://www.redbus.in/bus-tickets/illambazar-t...,Illambazar to Kolkata
31,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Bajkul (West Bengal)
32,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Debra
33,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Midnapore
34,https://www.redbus.in/bus-tickets/kolkata-to-r...,Kolkata to Ramnagar (West Bengal)
35,https://www.redbus.in/bus-tickets/kolkata-to-k...,Kolkata to Kirnahar (West Bengal)
36,https://www.redbus.in/bus-tickets/kolkata-to-j...,Kolkata to Jhargram
37,https://www.redbus.in/bus-tickets/kolkata-to-p...,Kolkata to Panskura
38,https://www.redbus.in/bus-tickets/berhampore-t...,Berhampore (West Bengal) to Bolpur (West Bengal)
39,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Bankura
40,https://www.redbus.in/bus-tickets/kirnahar-wes...,Kirnahar (West Bengal) to Burdwan
41,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata
42,https://www.redbus.in/bus-tickets/futishanko-t...,Futishanko to Kolkata

In [33]:
# South bengal

driver = webdriver.Chrome()
driver.maximize_window()
sb_bus_name = []
sb_bus_type = []
sb_departing_time = []
sb_duration = []
sb_reaching_time = []
sb_star_rating = []
sb_price = []
sb_route_names = []
sb_route_link = []
sb_seat = []
for i , r in df_SB.iterrows():
    link = r['SB_link'] # ,
    routes = r['SB_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            sb_bus_name.append(Bus_name.text)
            sb_bus_type.append(Bus_type.text)
            sb_departing_time.append(Departing_time.text)
            sb_duration.append(Duration.text)
            sb_reaching_time.append(Reaching_time.text)
            sb_price.append(price.text)
            sb_star_rating.append(star_rating)
            sb_route_link.append(link)
            sb_route_names.append(routes)    
            sb_seat.append(seat)

In [36]:
# print(len(sb_bus_name))
# print(len(sb_bus_type))
# print(len(sb_departing_time))
# print(len(sb_duration))
# print(len(sb_reaching_time))
# print(len(sb_star_rating))
# print(len(sb_price))
# print(len(sb_route_names))
# print(len(sb_route_link))

In [37]:
data4 = {'route_name':sb_route_names,'route_link':sb_route_link,'busname':sb_bus_name,
         'bustype':sb_bus_type,'departing_time':sb_departing_time,'duration':sb_duration,
         'reaching_time':sb_reaching_time,'star_rating':sb_star_rating,'price':sb_price,
         'seats_available':sb_seat}
df_state_4 = pd.DataFrame(data4)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\SBbusdetails.csv'
df_state_4.to_csv(path,index=False)

In [38]:
df_buses_4 = pd.read_csv('SBbusdetails.csv')
df_buses_4

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Durgapur (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/durgapur-to-...,SBSTC-BANKURA - KARUNAMOYEE - A/C - 15:15 - 1500,AC Seater (2+2),17:00,04h 00m,21:00,2.2,INR 300,1 Seat available
1,Durgapur (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/durgapur-to-...,SBSTC-ASANSOL - KARUNAMOYEE - 16:10 (BEL DEPOT...,Non AC Seater (2+3),17:25,04h 00m,21:25,4.0,INR 155,4 Seats available
2,Durgapur (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/durgapur-to-...,SBSTC-ASANSOL - KOLKATA - 16:30 (HOWRAH DEPOT)...,Non AC Seater (2+3),17:40,03h 30m,21:10,3.5,INR 150,29 Seats available
3,Durgapur (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/durgapur-to-...,SBSTC-ASANSOL - KARUNAMOYEE - 16:40 (ASANSOL D...,Non AC Seater (2+3),17:50,04h 10m,22:00,3.1,INR 155,16 Seats available
4,Durgapur (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/durgapur-to-...,WBTC (CTC) KARUNAMOYEE - DURGAPUR - ASANSOL (A...,Volvo AC Seater (2+2),17:10,03h 15m,20:25,4.4,INR 350,15 Seats available
...,...,...,...,...,...,...,...,...,...,...
310,Siliguri to Kolkata,https://www.redbus.in/bus-tickets/siliguri-to-...,Maa Durga Bus Service,NON AC Seater / Sleeper 2+1,18:30,13h 30m,08:00,3.1,INR 600,5 Seats available
311,Siliguri to Kolkata,https://www.redbus.in/bus-tickets/siliguri-to-...,Royal Cruiser,Scania Multi-Axle AC Semi Sleeper (2+2),17:35,13h 00m,06:35,3.6,INR 1200,6 Seats available
312,Siliguri to Kolkata,https://www.redbus.in/bus-tickets/siliguri-to-...,Maulik Paribahan,A/C Seater / Sleeper (2+2),18:30,11h 30m,06:00,2.0,INR 1000,44 Seats available
313,Siliguri to Kolkata,https://www.redbus.in/bus-tickets/siliguri-to-...,Annesha Travels,NON A/C Seater / Sleeper (2+2),18:00,13h 00m,07:00,2.3,INR 500,17 Seats available
314,Siliguri to Kolkata,https://www.redbus.in/bus-tickets/siliguri-to-...,Gopal Travels,A/C Seater / Sleeper (2+2),20:00,12h 10m,08:10,2.0,INR 1100,65 Seats available

In [39]:
df_hr = pd.read_csv('df_hr.csv')
df_hr

,hrtc_link,hrtc_route
0,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla
1,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh
2,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Hamirpur (Himachal Pradesh)
3,https://www.redbus.in/bus-tickets/shimla-to-delhi,Shimla to Delhi
4,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Delhi
5,https://www.redbus.in/bus-tickets/delhi-to-ham...,Delhi to Hamirpur (Himachal Pradesh)
6,https://www.redbus.in/bus-tickets/kangra-to-ch...,Kangra to Chandigarh
7,https://www.redbus.in/bus-tickets/chamba-himac...,Chamba (Himachal Pradesh) to Chandigarh
8,https://www.redbus.in/bus-tickets/delhi-to-cha...,Delhi to Chandigarh
9,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
10,https://www.redbus.in/bus-tickets/dharamshala-...,Dharamshala (Himachal Pradesh) to Chandigarh
11,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Dharamshala (Himachal Pradesh)
12,https://www.redbus.in/bus-tickets/delhi-to-cha...,Delhi to Chamba (Himachal Pradesh)
13,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Palampur
14,https://www.redbus.in/bus-tickets/delhi-to-nal...,Delhi to Nalagarh
15,https://www.redbus.in/bus-tickets/shimla-to-ch...,Shimla to Chandigarh
16,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Kangra
17,https://www.redbus.in/bus-tickets/ghumarwin-to...,Ghumarwin to Chandigarh
18,https://www.redbus.in/bus-tickets/chamba-himac...,Chamba (Himachal Pradesh) to Delhi
19,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Kullu
20,https://www.redbus.in/bus-tickets/manali-to-ch...,Manali to Chandigarh
21,https://www.redbus.in/bus-tickets/delhi-to-solan,Delhi to Solan
22,https://www.redbus.in/bus-tickets/shimla-to-ma...,Shimla to Manali
23,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Manali
24,https://www.redbus.in/bus-tickets/kullu-to-shimla,Kullu to Shimla
25,https://www.redbus.in/bus-tickets/jassur-to-ch...,Jassur to Chandigarh
26,https://www.redbus.in/bus-tickets/solan-to-delhi,Solan to Delhi
27,https://www.redbus.in/bus-tickets/sundernagar-...,Sunder Nagar (Himachal Pradesh) to Chandigarh
28,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Sarkaghat
29,https://www.redbus.in/bus-tickets/delhi-to-bil...,Delhi to Bilaspur (Himachal Pradesh)
30,https://www.redbus.in/bus-tickets/kangra-to-delhi,Kangra to Delhi
31,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Delhi
32,https://www.redbus.in/bus-tickets/delhi-to-pal...,Delhi to Palampur
33,https://www.redbus.in/bus-tickets/delhi-to-sar...,Delhi to Sarkaghat
34,https://www.redbus.in/bus-tickets/ghumarwin-to...,Ghumarwin to Delhi
35,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla
36,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi

In [40]:
# HR 
driver = webdriver.Chrome()
driver.maximize_window()
hr_bus_name = []
hr_bus_type = []
hr_departing_time = []
hr_duration = []
hr_reaching_time = []
hr_star_rating = []
hr_price = []
hr_route_names = []
hr_route_link = []
hr_seat = []
for i , r in df_hr.iterrows():
    link = r['hrtc_link'] # ,
    routes = r['hrtc_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            hr_bus_name.append(Bus_name.text)
            hr_bus_type.append(Bus_type.text)
            hr_departing_time.append(Departing_time.text)
            hr_duration.append(Duration.text)
            hr_reaching_time.append(Reaching_time.text)
            hr_price.append(price.text)
            hr_star_rating.append(star_rating)
            hr_route_link.append(link)
            hr_route_names.append(routes)    
            hr_seat.append(seat)

In [41]:
data5 = {'route_name':hr_route_names,'route_link':hr_route_link,'busname':hr_bus_name,
         'bustype':hr_bus_type,'departing_time':hr_departing_time,'duration':hr_duration,
         'reaching_time':hr_reaching_time,'star_rating':hr_star_rating,'price':hr_price,
         'seats_available':hr_seat}
df_state_5 = pd.DataFrame(data5)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\hrtcbusdetails.csv'
df_state_5.to_csv(path,index=False)

In [43]:
df_buses_5 = pd.read_csv('hrtcbusdetails.csv')
df_buses_5

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 532,Ordinary 3+2 Non AC Seater,17:59,10h 16m,04:15,1.5,INR 512,24 Seats available
1,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 301,Ordinary 3+2 Non AC Seater,19:43,09h 47m,05:30,4.5,INR 512,27 Seats available
2,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 591,A/C Executive (2+3),21:00,10h 20m,07:20,3.0,INR 632,36 Seats available
3,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 570,Ordinary 3+2 Non AC Seater,21:25,09h 20m,06:45,3.2,INR 512,34 Seats available
4,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 9,Himsuta AC Seater Volvo/Scania 2+2,22:00,09h 30m,07:30,3.9,INR 912,3 Seats available
...,...,...,...,...,...,...,...,...,...,...
750,Manali to Shimla,https://www.redbus.in/bus-tickets/manali-to-sh...,HRTC - 710,Himmani Deluxe 2+2 Non AC Seater,18:20,10h 10m,04:30,3.6,INR 641,27 Seats available
751,Manali to Shimla,https://www.redbus.in/bus-tickets/manali-to-sh...,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00,09h 10m,06:10,3.9,INR 963,26 Seats available
752,Manali to Shimla,https://www.redbus.in/bus-tickets/manali-to-sh...,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30,09h 05m,06:35,4.0,INR 583,32 Seats available
753,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30,07h 10m,02:40,3.8,INR 325,35 Seats available
754,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6639,A/C Executive (2+3),20:45,06h 45m,03:30,3.7,INR 430,36 Seats available

In [44]:
df_astc = pd.read_csv('df_astc.csv')
df_astc

,ASTC_link,ASTC_route
0,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati
1,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur
2,https://www.redbus.in/bus-tickets/nagaon-to-gu...,Nagaon (Assam) to Guwahati
3,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Nagaon (Assam)
4,https://www.redbus.in/bus-tickets/goalpara-to-...,Goalpara to Guwahati
5,https://www.redbus.in/bus-tickets/dhubri-to-gu...,Dhubri to Guwahati
6,https://www.redbus.in/bus-tickets/sibsagar-to-...,Sibsagar (Assam) to North Lakhimpur
7,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Sibsagar (Assam)
8,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Dhubri
9,https://www.redbus.in/bus-tickets/jorhat-to-no...,Jorhat to North Lakhimpur
10,https://www.redbus.in/bus-tickets/dhekiajuli-t...,Dhekiajuli to Guwahati
11,https://www.redbus.in/bus-tickets/jorhat-to-di...,Jorhat to Dibrugarh
12,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Jorhat
13,https://www.redbus.in/bus-tickets/jorhat-to-dh...,Jorhat to Dhemaji
14,https://www.redbus.in/bus-tickets/dhemaji-to-j...,Dhemaji to Jorhat
15,https://www.redbus.in/bus-tickets/jorhat-to-ti...,Jorhat to Tinsukia
16,https://www.redbus.in/bus-tickets/tezpur-to-di...,Tezpur to Dibrugarh
17,https://www.redbus.in/bus-tickets/tinsukia-to-...,Tinsukia to Jorhat
18,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Jorhat
19,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Dibrugarh
20,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Biswanath Charali
21,https://www.redbus.in/bus-tickets/biswanath-ch...,Biswanath Charali to Guwahati
22,https://www.redbus.in/bus-tickets/biswanath-ch...,Biswanath Charali to Dibrugarh
23,https://www.redbus.in/bus-tickets/sibsagar-to-...,Sibsagar (Assam) to Dhemaji
24,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Tezpur
25,https://www.redbus.in/bus-tickets/bokakhat-to-...,Bokakhat to Dibrugarh
26,https://www.redbus.in/bus-tickets/moran-to-tezpur,Moran to Tezpur
27,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to North Lakhimpur
28,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Tezpur
29,https://www.redbus.in/bus-tickets/bihpuria-to-...,Bihpuria to Dibrugarh
30,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Moran
31,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Biswanath Charali
32,https://www.redbus.in/bus-tickets/golaghat-to-...,Golaghat to North Lakhimpur
33,https://www.redbus.in/bus-tickets/moran-to-nor...,Moran to North Lakhimpur
34,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Silchar
35,https://www.redbus.in/bus-tickets/gohpur-to-di...,Gohpur to Dibrugarh
36,https://www.redbus.in/bus-tickets/tinsukia-to-...,Tinsukia to Tezpur
37,https://www.redbus.in/bus-tickets/gohpur-to-gu...,Gohpur to Guwahati
38,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Gohpur
39,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Kaliabor
40,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Guwahati
41,https://www.redbus.in/bus-tickets/tezpur-to-ti...,Tezpur to Tinsukia
42,https://www.redbus.in/bus-tickets/dergaon-to-d...,Dergaon to Dibrugarh
43,https://www.redbus.in/bus-tickets/tezpur-to-moran,Tezpur to Moran
44,https://www.redbus.in/bus-tickets/tezpur-to-no...,Tezpur to North Lakhimpur
45,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam)
46,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tumuki (Tezpur Medical)

In [49]:
# astc
driver = webdriver.Chrome()
driver.maximize_window()
astc_bus_name = []
astc_bus_type = []
astc_departing_time = []
astc_duration = []
astc_reaching_time = []
astc_star_rating = []
astc_price = []
astc_route_names = []
astc_route_link = []
astc_seat = []
for i , r in df_astc.iterrows():
    link = r['ASTC_link'] # ,
    routes = r['ASTC_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            astc_bus_name.append(Bus_name.text)
            astc_bus_type.append(Bus_type.text)
            astc_departing_time.append(Departing_time.text)
            astc_duration.append(Duration.text)
            astc_reaching_time.append(Reaching_time.text)
            astc_price.append(price.text)
            astc_star_rating.append(star_rating)
            astc_route_link.append(link)
            astc_route_names.append(routes)    
            astc_seat.append(seat)

In [50]:
print(astc_route_link)

['https://www.redbus.in/bus-tickets/tezpur-to-guwahati', 'https://www.redbus.in/bus-tickets/tezpur-to-guwahati', 'https://www.redbus.in/bus-tickets/tezpur-to-guwahati', 'https://www.redbus.in/bus-tickets/tezpur-to-guwahati', 'https://www.redbus.in/bus-tickets/tezpur-to-guwahati', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-tezpur', 'https://www.redbus.in/bus-tickets/guwahati-to-nagaon', 'https://www.redbus.in/bus-tickets/dhubri-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-sibsagar', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-jorhat', 'https://www.redbus.in/bus-tickets/tezpur-to-dibrugarh', 'https://www.redbus.in/bus-tickets/tezpur-to-dibrugarh', 'https://www.redbus.in/bus-tickets/tezpur-to-dibrugarh', 'https://www.redbus.in/bus-tickets/tezpur-to-dibrugarh', 'https://www.redbus.in/bus-tickets/tinsukia-to-jorhat', 'https://www.redbus.in/bus-tickets/tinsukia-to-jorhat', 'https://www.redbus.in/bus-tickets/dibrugarh-to-jorhat', 'https://www.redbus.in/bus-tickets/dibrugarh-to-jorhat', 'https://www.redbus.in/bus-tickets/dibrugarh-to-jorhat', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati', 'https://www.redbus.in/bus-tickets/dibrugarh-to-tezpur', 'https://www.redbus.in/bus-tickets/dibrugarh-to-tezpur', 'https://www.redbus.in/bus-tickets/dibrugarh-to-tezpur', 'https://www.redbus.in/bus-tickets/bokakhat-to-dibrugarh', 'https://www.redbus.in/bus-tickets/bokakhat-to-dibrugarh', 'https://www.redbus.in/bus-tickets/moran-to-tezpur', 'https://www.redbus.in/bus-tickets/moran-to-tezpur', 'https://www.redbus.in/bus-tickets/moran-to-tezpur', 'https://www.redbus.in/bus-tickets/moran-to-tezpur', 'https://www.redbus.in/bus-tickets/dibrugarh-to-north-lakhimpur', 'https://www.redbus.in/bus-tickets/dibrugarh-to-north-lakhimpur', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-tezpur', 'https://www.redbus.in/bus-tickets/dibrugarh-to-biswanath-charali', 'https://www.redbus.in/bus-tickets/tinsukia-to-tezpur', 'https://www.redbus.in/bus-tickets/tinsukia-to-tezpur', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/gohpur-to-guwahati', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-gohpur', 'https://www.redbus.in/bus-tickets/guwahati-to-kaliabor', 'https://www.redbus.in/bus-tickets/guwahati-to-kaliabor', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati', 'https://www.redbus.in/bus-tickets/tezpur-to-tinsukia', 'https://www.redbus.in/bus-tickets/tezpur-to-tinsukia', 'https://www.redbus.in/bus-tickets/tezpur-to-tinsukia', 'https://www.redbus.in/bus-tickets/tezpur-to-tinsukia', 'https://www.redbus.in/bus-tickets/tezpur-to-moran', 'https://www.redbus.in/bus-tickets/tezpur-to-moran', 'https://www.redbus.in/bus-tickets/tezpur-to-north-lakhimpur', 'https://www.redbus.in/bus-tickets/tezpur-to-north-lakhimpur', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon', 'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon']

In [51]:
data6 = {'route_name':astc_route_names,'route_link':astc_route_link,'busname':astc_bus_name,
         'bustype':astc_bus_type,'departing_time':astc_departing_time,'duration':astc_duration,
         'reaching_time':astc_reaching_time,'star_rating':astc_star_rating,'price':astc_price,
         'seats_available':astc_seat}
df_state_6 = pd.DataFrame(data6)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\astcbusdetails.csv'
df_state_6.to_csv(path,index=False)

In [53]:
df_buses_6 = pd.read_csv('astcbusdetails.csv')
df_buses_6

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:15,05h 45m,03:00,3.5,INR 450,15 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:45,05h 30m,03:15,3.5,450,15 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Shopuris Travels,Non AC Seater (2+1),21:15,05h 45m,03:00,2.9,525,22 Seats available
3,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Shopuris Travels,Non AC Seater (2+1),23:15,05h 05m,04:20,2.9,525,23 Seats available
4,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Himalayan Travels,NON AC Seater / Sleeper 2+1,23:40,04h 20m,04:00,1.7,INR 500,30 Seats available
...,...,...,...,...,...,...,...,...,...,...
150,North Lakhimpur to Nagaon (Assam),https://www.redbus.in/bus-tickets/north-lakhim...,Yatra Travels,NON AC Seater/ Sleeper (2+1),20:30,08h 00m,04:30,4.6,450,26 Seats available
151,North Lakhimpur to Nagaon (Assam),https://www.redbus.in/bus-tickets/north-lakhim...,Yatra Travels,NON A/C Seater (2+1),20:40,06h 20m,03:00,4.1,450,20 Seats available
152,North Lakhimpur to Nagaon (Assam),https://www.redbus.in/bus-tickets/north-lakhim...,PARIJAT TRAVELS(UNDER ASTC),NON A/C Seater (2+1),20:56,06h 04m,03:00,3.9,INR 590,17 Seats available
153,North Lakhimpur to Nagaon (Assam),https://www.redbus.in/bus-tickets/north-lakhim...,Yatra Travels,A/C Seater / Sleeper (2+1),21:00,06h 30m,03:30,4.1,500,17 Seats available
154,North Lakhimpur to Nagaon (Assam),https://www.redbus.in/bus-tickets/north-lakhim...,KIRAN TRAVELS,A/C Seater (2+1),21:20,07h 10m,04:30,2.8,578,11 Seats available

In [56]:
df_upsrtc = pd.read_csv('df_upsrtc.csv')
df_upsrtc

,UPSRTC_link,UPSRTC_route
0,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh)
1,https://www.redbus.in/bus-tickets/delhi-to-luc...,Delhi to Lucknow
2,https://www.redbus.in/bus-tickets/bareilly-to-...,Bareilly (Uttar Pradesh) to Delhi
3,https://www.redbus.in/bus-tickets/lucknow-to-g...,Lucknow to Gorakhpur (uttar pradesh)
4,https://www.redbus.in/bus-tickets/aligarh-utta...,Aligarh (uttar pradesh) to Delhi
5,https://www.redbus.in/bus-tickets/lucknow-to-a...,Lucknow to Prayagraj(Uttar Pradesh)
6,https://www.redbus.in/bus-tickets/delhi-to-ali...,Delhi to Aligarh (uttar pradesh)
7,https://www.redbus.in/bus-tickets/lucknow-to-d...,Lucknow to Delhi
8,https://www.redbus.in/bus-tickets/allahabad-to...,Prayagraj(Uttar Pradesh) to Lucknow
9,https://www.redbus.in/bus-tickets/delhi-to-far...,Delhi to Farrukhabad (Uttar Pradesh)
10,https://www.redbus.in/bus-tickets/delhi-to-sit...,Delhi to Sitapur (Uttar Pradesh)
11,https://www.redbus.in/bus-tickets/agra-to-lucknow,Agra to Lucknow
12,https://www.redbus.in/bus-tickets/delhi-to-gor...,Delhi to Gorakhpur (uttar pradesh)
13,https://www.redbus.in/bus-tickets/farrukhabad-...,Farrukhabad (Uttar Pradesh) to Delhi
14,https://www.redbus.in/bus-tickets/lucknow-to-v...,Lucknow to Varanasi
15,https://www.redbus.in/bus-tickets/delhi-to-mor...,Delhi to Moradabad
16,https://www.redbus.in/bus-tickets/lucknow-to-b...,Lucknow to Ballia (Uttar Pradesh)
17,https://www.redbus.in/bus-tickets/aligarh-to-l...,Aligarh (uttar pradesh) to Lucknow
18,https://www.redbus.in/bus-tickets/moradabad-to...,Moradabad to Delhi
19,https://www.redbus.in/bus-tickets/sitapur-to-d...,Sitapur (Uttar Pradesh) to Delhi
20,https://www.redbus.in/bus-tickets/delhi-to-sha...,Delhi to Shahjahanpur (Uttar Pradesh)
21,https://www.redbus.in/bus-tickets/greater-noid...,Greater noida (uttar pradesh) to Lucknow
22,https://www.redbus.in/bus-tickets/kanpur-to-va...,Kanpur (Uttar Pradesh) to Varanasi
23,https://www.redbus.in/bus-tickets/gorakhpur-to...,Gorakhpur (uttar pradesh) to Lucknow
24,https://www.redbus.in/bus-tickets/delhi-to-agra,Delhi to Agra
25,https://www.redbus.in/bus-tickets/delhi-to-badaun,Delhi to Badaun
26,https://www.redbus.in/bus-tickets/delhi-to-kanpur,Delhi to Kanpur (Uttar Pradesh)
27,https://www.redbus.in/bus-tickets/delhi-to-pil...,Delhi to Pilibhit
28,https://www.redbus.in/bus-tickets/lucknow-to-m...,Lucknow to Mathura
29,https://www.redbus.in/bus-tickets/kanpur-to-ba...,Kanpur (Uttar Pradesh) to Bareilly (Uttar Prad...
30,https://www.redbus.in/bus-tickets/bareilly-to-...,Bareilly (Uttar Pradesh) to Lucknow
31,https://www.redbus.in/bus-tickets/dehradun-to-...,Dehradun to Bareilly (Uttar Pradesh)
32,https://www.redbus.in/bus-tickets/badaun-to-delhi,Badaun to Delhi
33,https://www.redbus.in/bus-tickets/agra-to-bare...,Agra to Bareilly (Uttar Pradesh)
34,https://www.redbus.in/bus-tickets/ballia-to-lu...,Ballia (Uttar Pradesh) to Lucknow
35,https://www.redbus.in/bus-tickets/delhi-to-kot...,Delhi to Kotdwar (Uttarakhand)
36,https://www.redbus.in/bus-tickets/lucknow-to-agra,Lucknow to Agra
37,https://www.redbus.in/bus-tickets/agra-to-delhi,Agra to Delhi
38,https://www.redbus.in/bus-tickets/gorakhpur-to...,Gorakhpur (uttar pradesh) to Delhi
39,https://www.redbus.in/bus-tickets/bareilly-to-...,Bareilly (Uttar Pradesh) to Dehradun
40,https://www.redbus.in/bus-tickets/jhansi-to-ka...,Jhansi(Uttar Pradesh) to Kanpur (Uttar Pradesh)
41,https://www.redbus.in/bus-tickets/mathura-to-l...,Mathura to Lucknow
42,https://www.redbus.in/bus-tickets/varanasi-to-...,Varanasi to Lucknow
43,https://www.redbus.in/bus-tickets/lucknow-to-b...,Lucknow to Bareilly (Uttar Pradesh)
44,https://www.redbus.in/bus-tickets/bareilly-to-...,Bareilly (Uttar Pradesh) to Agra
45,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani
46,https://www.redbus.in/bus-tickets/allahabad-to...,Prayagraj(Uttar Pradesh) to Azamgarh
47,https://www.redbus.in/bus-tickets/shahjahanpur...,Shahjahanpur (Uttar Pradesh) to Delhi

In [58]:
# UPSRTC
driver = webdriver.Chrome()
driver.maximize_window()
upsrtc_bus_name = []
upsrtc_bus_type = []
upsrtc_departing_time = []
upsrtc_duration = []
upsrtc_reaching_time = []
upsrtc_star_rating = []
upsrtc_price = []
upsrtc_route_names = []
upsrtc_route_link = []
upsrtc_seat = []
for i , r in df_upsrtc.iterrows():
    link = r['UPSRTC_link'] # ,
    routes = r['UPSRTC_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            upsrtc_bus_name.append(Bus_name.text)
            upsrtc_bus_type.append(Bus_type.text)
            upsrtc_departing_time.append(Departing_time.text)
            upsrtc_duration.append(Duration.text)
            upsrtc_reaching_time.append(Reaching_time.text)
            upsrtc_price.append(price.text)
            upsrtc_star_rating.append(star_rating)
            upsrtc_route_link.append(link)
            upsrtc_route_names.append(routes)    
            upsrtc_seat.append(seat)

In [59]:
data7 = {'route_name':upsrtc_route_names,'route_link':upsrtc_route_link,'busname':upsrtc_bus_name,
         'bustype':upsrtc_bus_type,'departing_time':upsrtc_departing_time,'duration':upsrtc_duration,
         'reaching_time':upsrtc_reaching_time,'star_rating':upsrtc_star_rating,'price':upsrtc_price,
         'seats_available':upsrtc_seat}
df_state_7 = pd.DataFrame(data7)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\upsrtcbusdetails.csv'
df_state_7.to_csv(path,index=False)

In [62]:
df_buses_7 = pd.read_csv('upsrtcbusdetails.csv')
df_buses_7

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - HDD0147,Ordinary Non AC Seater 2+3,20:03,05h 58m,02:01,3.3,INR 444,52 Seats available
1,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - BRT0063,Ordinary Non AC Seater 2+3,20:30,07h 10m,03:40,3.3,INR 492,52 Seats available
2,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - RKD0153,Ordinary Non AC Seater 2+3,21:00,05h 30m,02:30,3.3,INR 448,52 Seats available
3,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - RKD0723,Ordinary Non AC Seater 2+3,21:06,05h 34m,02:40,1.0,INR 454,52 Seats available
4,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - SJP0210,Ordinary Non AC Seater 2+3,21:12,05h 34m,02:46,3.3,INR 499,52 Seats available
...,...,...,...,...,...,...,...,...,...,...
1249,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - STD0144,Ordinary Non AC Seater 2+3,21:28,09h 02m,06:30,3.3,INR 613,52 Seats available
1250,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - SJP0288,Ordinary Non AC Seater 2+3,21:45,07h 20m,05:05,3.3,INR 634,49 Seats available
1251,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - STD0072,Janrath AC Seater 2+2,22:40,07h 05m,05:45,2.5,INR 818,11 Seats available
1252,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - LKM0401,Shatabdi AC Seater 2+2,22:55,07h 19m,06:14,3.3,INR 841,37 Seats available
1253,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - KSB0221,Shatabdi AC Seater 2+2,23:30,06h 30m,06:00,3.3,INR 818,26 Seats available

In [63]:
df_wbtc = pd.read_csv('df_wbtc.csv')
df_wbtc

,WBTC_link,WBTC_route
0,https://www.redbus.in/bus-tickets/digha-to-bar...,Digha to Barasat (West Bengal)
1,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata
2,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata
3,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Digha
4,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Durgapur (West Bengal)
5,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha
6,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Contai (Kanthi)
7,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Midnapore
8,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Nandakumar (west bengal)
9,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Kolaghat
10,https://www.redbus.in/bus-tickets/kolkata-to-suri,Kolkata to Suri
11,https://www.redbus.in/bus-tickets/midnapore-to...,Midnapore to Kolkata
12,https://www.redbus.in/bus-tickets/midnapore-to...,Midnapore to Barasat (West Bengal)
13,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Durgapur (West Bengal)
14,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Heria
15,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Bolpur (West Bengal)
16,https://www.redbus.in/bus-tickets/habra-to-digha,Habra to Digha
17,https://www.redbus.in/bus-tickets/kolkata-to-a...,Kolkata to Asansol (West Bengal)
18,https://www.redbus.in/bus-tickets/digha-to-habra,Digha to Habra
19,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Haldia
20,https://www.redbus.in/bus-tickets/haldia-to-ba...,Haldia to Barasat (West Bengal)
21,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mayapur ISKCON
22,https://www.redbus.in/bus-tickets/haldia-to-ko...,Haldia to Kolkata
23,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Burdwan
24,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Chowrangee(Kharagpur)
25,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Burdwan
26,https://www.redbus.in/bus-tickets/kolkata-to-b...,Kolkata to Bakkhali
27,https://www.redbus.in/bus-tickets/habra-to-nan...,Habra to Nandakumar (west bengal)
28,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Purulia
29,https://www.redbus.in/bus-tickets/jayrambati-w...,Jayrambati (West Bengal) to Barasat (West Bengal)
30,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Debra
31,https://www.redbus.in/bus-tickets/habra-to-mid...,Habra to Midnapore
32,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Barasat (West Bengal)
33,https://www.redbus.in/bus-tickets/habra-to-dur...,Habra to Durgapur (West Bengal)
34,https://www.redbus.in/bus-tickets/kolkata-to-p...,Kolkata to Purulia
35,https://www.redbus.in/bus-tickets/barasat-west...,Barasat (West Bengal) to Asansol (West Bengal)
36,https://www.redbus.in/bus-tickets/habra-to-kol...,Habra to Kolaghat
37,https://www.redbus.in/bus-tickets/kolkata-to-h...,Kolkata to Haldia

In [64]:
# WBTC
driver = webdriver.Chrome()
driver.maximize_window()
wbtc_bus_name = []
wbtc_bus_type = []
wbtc_departing_time = []
wbtc_duration = []
wbtc_reaching_time = []
wbtc_star_rating = []
wbtc_price = []
wbtc_route_names = []
wbtc_route_link = []
wbtc_seat = []
for i , r in df_wbtc.iterrows():
    link = r['WBTC_link'] # 
    routes = r['WBTC_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            wbtc_bus_name.append(Bus_name.text)
            wbtc_bus_type.append(Bus_type.text)
            wbtc_departing_time.append(Departing_time.text)
            wbtc_duration.append(Duration.text)
            wbtc_reaching_time.append(Reaching_time.text)
            wbtc_price.append(price.text)
            wbtc_star_rating.append(star_rating)
            wbtc_route_link.append(link)
            wbtc_route_names.append(routes)    
            wbtc_seat.append(seat)

In [65]:
data8 = {'route_name':wbtc_route_names,'route_link':wbtc_route_link,'busname':wbtc_bus_name,
         'bustype':wbtc_bus_type,'departing_time':wbtc_departing_time,'duration':wbtc_duration,
         'reaching_time':wbtc_reaching_time,'star_rating':wbtc_star_rating,'price':wbtc_price,
         'seats_available':wbtc_seat}
df_state_8 = pd.DataFrame(data8)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\wbtcbusdetails.csv'
df_state_8.to_csv(path,index=False)

In [66]:
df_buses_8 = pd.read_csv('wbtcbusdetails.csv')
df_buses_8

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Esplanade - 176|04:00,Non AC Seater (2+3),04:00,05h 50m,09:50,4.3,INR 165,33 Seats available
1,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) BARASAT-DIGHA via Bally - 38|05:40,Non AC Seater (2+3),05:40,04h 30m,10:10,3.5,INR 161,24 Seats available
2,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:00,Non AC Seater (2+3),10:00,04h 45m,14:45,3.3,INR 161,28 Seats available
3,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:40,Non AC Seater (2+3),10:40,04h 45m,15:25,3.1,INR 161,26 Seats available
4,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|11:30,Non AC Seater (2+3),11:30,04h 45m,16:15,3.9,INR 161,43 Seats available
...,...,...,...,...,...,...,...,...,...,...
1233,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi City Service,A/C Seater (2+3),15:20,02h 50m,18:10,3.0,180,56 Seats available
1234,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Swapna Paribahan,Non AC Seater (2+3),16:55,04h 30m,21:25,3.0,INR 150,25 Seats available
1235,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Paribahan,A/C Seater (2+3),14:10,02h 48m,16:58,2.7,INR 160,61 Seats available
1236,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,KRISHNAKALI,A/C Seater (2+3),14:45,02h 45m,17:30,2.2,INR 165,61 Seats available
1237,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Bus Service,Non AC Seater (2+3),16:20,02h 50m,19:10,2.2,INR 121,54 Seats available

In [67]:
df_ctu = pd.read_csv('df_ctu.csv')
df_ctu

,CTU_link,CTC_route
0,https://www.redbus.in/bus-tickets/delhi-to-cha...,Delhi to Chandigarh
1,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Delhi
2,https://www.redbus.in/bus-tickets/yamuna-nagar...,Yamuna Nagar to Chandigarh
3,https://www.redbus.in/bus-tickets/ludhiana-to-...,Ludhiana to Chandigarh
4,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Yamuna Nagar
5,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Hamirpur (Himachal Pradesh)
6,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Baijnath
7,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh
8,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Ludhiana
9,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Dehradun
10,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Sujanpur (himachal pradesh)
11,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Vrindavan
12,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Pathankot
13,https://www.redbus.in/bus-tickets/dehradun-to-...,Dehradun to Chandigarh
14,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Dharamshala (Himachal Pradesh)
15,https://www.redbus.in/bus-tickets/sujanpur-to-...,Sujanpur (himachal pradesh) to Chandigarh
16,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Dinanagar (punjab)
17,https://www.redbus.in/bus-tickets/vrindavan-to...,Vrindavan to Chandigarh
18,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Shimla
19,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Talwara
20,https://www.redbus.in/bus-tickets/dinanagar-pu...,Dinanagar (punjab) to Chandigarh
21,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Agra
22,https://www.redbus.in/bus-tickets/rohtak-to-ch...,Rohtak to Chandigarh
23,https://www.redbus.in/bus-tickets/talwara-to-c...,Talwara to Chandigarh
24,https://www.redbus.in/bus-tickets/dharamshala-...,Dharamshala (Himachal Pradesh) to Chandigarh
25,https://www.redbus.in/bus-tickets/pathankot-to...,Pathankot to Chandigarh
26,https://www.redbus.in/bus-tickets/baijnath-to-...,Baijnath to Chandigarh
27,https://www.redbus.in/bus-tickets/shimla-to-ch...,Shimla to Chandigarh
28,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Haridwar

In [ ]:
# CTU


driver = webdriver.Chrome()
driver.maximize_window()
ctu_bus_name = []
ctu_bus_type = []
ctu_departing_time = []
ctu_duration = []
ctu_reaching_time = []
ctu_star_rating = []
ctu_price = []
ctu_route_names = []
ctu_route_link = []
ctu_seat = []

for i , r in df_ctu.iterrows():
    link = r['CTU_link'] # 
    routes = r['CTC_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            ctu_bus_name.append(Bus_name.text)
            ctu_bus_type.append(Bus_type.text)
            ctu_departing_time.append(Departing_time.text)
            ctu_duration.append(Duration.text)
            ctu_reaching_time.append(Reaching_time.text)
            ctu_price.append(price.text)
            ctu_star_rating.append(star_rating)
            ctu_route_link.append(link)
            ctu_route_names.append(routes)    
            ctu_seat.append(seat)

In [69]:
data9 = {'route_name':ctu_route_names,'route_link':ctu_route_link,'busname':ctu_bus_name,
         'bustype':ctu_bus_type,'departing_time':ctu_departing_time,'duration':ctu_duration,
         'reaching_time':ctu_reaching_time,'star_rating':ctu_star_rating,'price':ctu_price,
         'seats_available':ctu_seat}
df_state_9 = pd.DataFrame(data9)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\ctubusdetails.csv'
df_state_9.to_csv(path,index=False)

In [70]:
df_buses_9 = pd.read_csv('ctubusdetails.csv')
df_buses_9

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 689,A/C Executive (2+3),05:20,05h 10m,10:30,1.6,INR 400,38 Seats available
1,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 505,Ordinary 3+2 Non AC Seater,06:40,05h 40m,12:20,3.9,INR 275,36 Seats available
2,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 6,Himsuta AC Seater Volvo/Scania 2+2,06:45,04h 15m,11:00,3.8,INR 543,24 Seats available
3,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 533,Ordinary 3+2 Non AC Seater,07:20,05h 10m,12:30,3.1,INR 290,37 Seats available
4,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 592,A/C Executive (2+3),08:05,06h 00m,14:05,2.2,INR 400,42 Seats available
...,...,...,...,...,...,...,...,...,...,...
1296,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,Vijay Tour and Travels,Volvo 9600 A/C Sleeper (2+1),23:30,05h 00m,04:30,3.9,INR 1049,34 Seats available
1297,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,City Land Travels,Volvo A/C Semi Sleeper (2+2),23:55,05h 06m,05:01,3.8,810,17 Seats available
1298,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),VE A/C Seater / Sleeper (2+1),23:55,05h 40m,05:35,4.1,INR 899,25 Seats available
1299,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,Laxmi holidays,VE A/C Semi Sleeper (2+2),23:55,06h 35m,06:30,4.7,INR 999,42 Seats available
1300,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,Om Sidh Express,Volvo A/C (2+2),23:55,03h 05m,03:00,3.3,523,38 Seats available

In [71]:
df_pepesu = pd.read_csv('df_pepesu.csv')
df_pepesu

,PEPSU_link,PEPSU_route
0,https://www.redbus.in/bus-tickets/delhi-to-pat...,Delhi to Patiala
1,https://www.redbus.in/bus-tickets/patiala-to-d...,Patiala to Delhi
2,https://www.redbus.in/bus-tickets/ludhiana-to-...,Ludhiana to Delhi
3,https://www.redbus.in/bus-tickets/delhi-to-lud...,Delhi to Ludhiana
4,https://www.redbus.in/bus-tickets/ludhiana-to-...,Ludhiana to Delhi Airport
5,https://www.redbus.in/bus-tickets/delhi-to-jal...,Delhi to Jalandhar
6,https://www.redbus.in/bus-tickets/delhi-airpor...,Delhi Airport to Patiala
7,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Patiala
8,https://www.redbus.in/bus-tickets/jalandhar-to...,Jalandhar to Delhi
9,https://www.redbus.in/bus-tickets/delhi-airpor...,Delhi Airport to Ludhiana
10,https://www.redbus.in/bus-tickets/jalandhar-to...,Jalandhar to Delhi Airport
11,https://www.redbus.in/bus-tickets/chandigarh-t...,Chandigarh to Bathinda
12,https://www.redbus.in/bus-tickets/phagwara-to-...,Phagwara to Delhi
13,https://www.redbus.in/bus-tickets/delhi-airpor...,Delhi Airport to Jalandhar
14,https://www.redbus.in/bus-tickets/delhi-to-amr...,Delhi to Amritsar
15,https://www.redbus.in/bus-tickets/phagwara-to-...,Phagwara to Delhi Airport
16,https://www.redbus.in/bus-tickets/delhi-to-pha...,Delhi to Phagwara
17,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi
18,https://www.redbus.in/bus-tickets/delhi-airpor...,Delhi Airport to Phagwara
19,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Delhi Airport
20,https://www.redbus.in/bus-tickets/delhi-airpor...,Delhi Airport to Kapurthala
21,https://www.redbus.in/bus-tickets/amritsar-to-...,Amritsar to Patiala
22,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala to Amritsar

In [72]:
# CTU


driver = webdriver.Chrome()
driver.maximize_window()
pe_bus_name = []
pe_bus_type = []
pe_departing_time = []
pe_duration = []
pe_reaching_time = []
pe_star_rating = []
pe_price = []
pe_route_names = []
pe_route_link = []
pe_seat = []

for i , r in df_pepesu.iterrows():
    link = r['PEPSU_link'] # 
    routes = r['PEPSU_route']

    driver.get(link)
    time.sleep(5)

    elements = driver.find_elements(By.XPATH,f"//a[contains(@href,'{link}')]")
    for url in elements:
        url.click()
        time.sleep(3)
    try:
        buttons = driver.find_element(By.XPATH,"//div[@class = 'button']")
        buttons.click()

    except:
        pass
    time.sleep(4)    


    previous_height = 0
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)  # Wait for content to load
        new_height = driver.execute_script("return document.body.scrollHeight;")
        if new_height == previous_height:
            break  # Stop when no new content is loaded
        previous_height = new_height
    
      

    bus_box = driver.find_elements(By.XPATH,'//div[@class="clearfix row-one"]')
    if not bus_box:
               pass
    else: 
        for busitems in bus_box:

            try:#travels lh-24 f-bold d-color
                Bus_name = busitems.find_element(By.XPATH,".//div[@class ='travels lh-24 f-bold d-color']")   
            except:
                Bus_name = None
            try:
                Bus_type = busitems.find_element(By.XPATH,'.//div[@class="bus-type f-12 m-top-16 l-color evBus"]')
            except:
                Bus_type = None 
            try: #dp-time f-19 d-color f-bold
                Departing_time = busitems.find_element(By.XPATH,".//div[@class='dp-time f-19 d-color f-bold']")
            except:
                    Departing_time = None
            try:        #dur l-color lh-24
                Duration = busitems.find_element(By.XPATH,'.//div[@class="dur l-color lh-24"]')
            except:
                    Duration = None
            try:   #bp-time f-19 d-color disp-Inline
                Reaching_time = busitems.find_element(By.XPATH,'.//div[@class="bp-time f-19 d-color disp-Inline"]')
            except:
                Reaching_time = None
            try:    
                price = busitems.find_element(By.XPATH,'.//div[@class="fare d-block"]')
            except:
                price = '0' 

            try:
                star_rating = busitems.find_element(By.XPATH, './/div[@class = "rating-sec lh-24"]').text
                star_rating = star_rating if star_rating.strip() else '0.0'
            except:
                 star_rating = '0.0'
                 
            try: # seat 
                seat = busitems.find_element(By.XPATH,'.//*[contains(@class, "seat-left")]').text
                seat = seat if seat.strip() else 'no seats available'
            except:
                 seat = 'no seats available'

        # Append details to respective lists
            pe_bus_name.append(Bus_name.text)
            pe_bus_type.append(Bus_type.text)
            pe_departing_time.append(Departing_time.text)
            pe_duration.append(Duration.text)
            pe_reaching_time.append(Reaching_time.text)
            pe_price.append(price.text)
            pe_star_rating.append(star_rating)
            pe_route_link.append(link)
            pe_route_names.append(routes)    
            pe_seat.append(seat)

In [73]:
data10 = {'route_name':pe_route_names,'route_link':pe_route_link,'busname':pe_bus_name,
         'bustype':pe_bus_type,'departing_time':pe_departing_time,'duration':pe_duration,
         'reaching_time':pe_reaching_time,'star_rating':pe_star_rating,'price':pe_price,
         'seats_available':pe_seat}
df_state_10 = pd.DataFrame(data10)
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\pepesubusdetails.csv'
df_state_10.to_csv(path,index=False)

In [74]:
df_buses_10 = pd.read_csv('pepesubusdetails.csv')
df_buses_10

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67085,Volvo AC Seater (2+2),02:00,06h 00m,08:00,4.0,INR 826,17 Seats available
1,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67085,Volvo AC Seater (2+2),03:00,05h 00m,08:00,4.7,INR 711,17 Seats available
2,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67069,Volvo AC Seater (2+2),06:40,06h 50m,13:30,4.9,INR 826,13 Seats available
3,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67069,Volvo AC Seater (2+2),08:00,05h 30m,13:30,4.3,INR 711,14 Seats available
4,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67160,Volvo AC Seater (2+2),11:45,05h 30m,17:15,4.6,INR 711,25 Seats available
...,...,...,...,...,...,...,...,...,...,...
1246,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,INR 469,54 Seats available
1247,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,INR 469,54 Seats available
1248,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,INR 465,51 Seats available
1249,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,INR 465,47 Seats available
1250,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,854,8 Seats available

In [6]:
df_buses_1 = pd.read_csv('apsrtc_busdetails.csv')
df_buses_2 = pd.read_csv('telubusdetails.csv')
df_buses_3 = pd.read_csv('kadamba_busdetails.csv')
df_buses_4 = pd.read_csv('SBbusdetails.csv')
df_buses_5 = pd.read_csv('hrtcbusdetails.csv')
df_buses_6 = pd.read_csv('astcbusdetails.csv')
df_buses_7 = pd.read_csv('upsrtcbusdetails.csv')
df_buses_8 = pd.read_csv('wbtcbusdetails.csv')
df_buses_9 = pd.read_csv('ctubusdetails.csv')
df_buses_10 = pd.read_csv('pepesubusdetails.csv')

In [7]:
import pandas as pd
final_df = pd.concat([df_buses_1,df_buses_2,df_buses_3,df_buses_4,df_buses_5,df_buses_6,df_buses_7,df_buses_8,
df_buses_9,df_buses_10],ignore_index = True)
final_df

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3859,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),15:15,06h 10m,21:25,3.1,INR 633,37 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3356,NIGHT RIDER (SEATER CUM SLEEPER),15:45,07h 00m,22:45,3.7,INR 595,20 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3546,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),16:15,06h 15m,22:30,3.7,INR 633,27 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3500,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:20,08h 25m,00:45,3.5,INR 436,20 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3376,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:45,06h 30m,23:15,4.8,INR 436,31 Seats available
...,...,...,...,...,...,...,...,...,...,...
12963,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,INR 469,54 Seats available
12964,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,INR 469,54 Seats available
12965,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,INR 465,51 Seats available
12966,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,INR 465,47 Seats available
12967,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,854,8 Seats available

In [8]:
final_df['price'] = final_df['price'].str.replace('INR', '').str.strip().astype(float)
final_df['price']

0        633.0
1        595.0
2        633.0
3        436.0
4        436.0
         ...
12963    469.0
12964    469.0
12965    465.0
12966    465.0
12967    854.0
Name: price, Length: 12968, dtype: float64

In [10]:
final_df['star_rating'] = final_df['star_rating'].astype(float)
final_df['star_rating']

0        3.1
1        3.7
2        3.7
3        3.5
4        4.8
        ...
12963    3.7
12964    3.7
12965    5.0
12966    3.6
12967    1.6
Name: star_rating, Length: 12968, dtype: float64

In [9]:
final_df

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3859,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),15:15,06h 10m,21:25,3.1,633.0,37 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3356,NIGHT RIDER (SEATER CUM SLEEPER),15:45,07h 00m,22:45,3.7,595.0,20 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3546,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),16:15,06h 15m,22:30,3.7,633.0,27 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3500,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:20,08h 25m,00:45,3.5,436.0,20 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3376,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:45,06h 30m,23:15,4.8,436.0,31 Seats available
...,...,...,...,...,...,...,...,...,...,...
12963,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,469.0,54 Seats available
12964,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,469.0,54 Seats available
12965,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,465.0,51 Seats available
12966,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,465.0,47 Seats available
12967,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,854.0,8 Seats available

In [ ]:
final_df['seats_available'] = final_df['seats_available'].str.extract('(\d+)').astype(float).fillna(0).astype(int)
final_df['seats_available']

In [17]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12968 entries, 0 to 12967
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   route_name       12968 non-null  object
 1   route_link       12968 non-null  object
 2   busname          12968 non-null  object
 3   bustype          12968 non-null  object
 4   departing_time   12968 non-null  object
 5   duration         12968 non-null  object
 6   reaching_time    12968 non-null  object
 7   star_rating      12968 non-null  float64
 8   price            12968 non-null  float64
 9   seats_available  12968 non-null  int64
dtypes: float64(2), int64(1), object(7)
memory usage: 1013.3+ KB

In [18]:
final_df

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3859,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),15:15,06h 10m,21:25,3.1,633.0,37
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3356,NIGHT RIDER (SEATER CUM SLEEPER),15:45,07h 00m,22:45,3.7,595.0,20
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3546,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),16:15,06h 15m,22:30,3.7,633.0,27
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3500,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:20,08h 25m,00:45,3.5,436.0,20
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3376,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:45,06h 30m,23:15,4.8,436.0,31
...,...,...,...,...,...,...,...,...,...,...
12963,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,469.0,54
12964,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,469.0,54
12965,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,465.0,51
12966,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,465.0,47
12967,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,854.0,8

In [22]:
path = r'C:\Users\ADMIN\Desktop\Redbus_Project\final_df.csv'
final_df.to_csv(path,index=False)

In [26]:
df_read = pd.read_csv('final_df.csv')
df_read

,route_name,route_link,busname,bustype,departing_time,duration,reaching_time,star_rating,price,seats_available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3859,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),15:15,06h 10m,21:25,3.1,633.0,37
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3356,NIGHT RIDER (SEATER CUM SLEEPER),15:45,07h 00m,22:45,3.7,595.0,20
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3546,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),16:15,06h 15m,22:30,3.7,633.0,27
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3500,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:20,08h 25m,00:45,3.5,436.0,20
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3376,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",16:45,06h 30m,23:15,4.8,436.0,31
...,...,...,...,...,...,...,...,...,...,...
12963,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,469.0,54
12964,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,469.0,54
12965,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,465.0,51
12966,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,465.0,47
12967,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,854.0,8

In [40]:
import mysql.connector 
import pymysql

connection = pymysql.connect(
    host = 'localhost',
    user = 'root',
    password = '12345',
    database = 'redbus_project'
)
print("connection = ", connection)
cursor = connection.cursor()
print("cursor = ", cursor)

connection =  <pymysql.connections.Connection object at 0x0000021D0C3126C0>
cursor =  <pymysql.cursors.Cursor object at 0x0000021D0C44D3A0>

In [41]:
cursor.execute("""create table bus_routes(id int primary key auto_increment,
 route_name varchar(250),
 route_link varchar(350),
 bus_name varchar(250),
 bus_type varchar(250),
 departing_time varchar(300),
 duration varchar(250),
 reaching_time varchar(250),
 star_rating float,
 price float,
 seats_available int
 )""")
print('created')
connection.commit()

created

In [42]:
insert_sql = """insert into bus_routes(route_name,
                                       route_link,
                                       bus_name,
                                       bus_type,
                                       departing_time,
                                       duration,
                                       reaching_time,
                                       star_rating,
                                       price,
                                       seats_available)
                                    Values(%s, %s, %s, %s, %s , %s, %s, %s, %s, %s)"""
  # Convert DataFrame to a list of tuples
values = [tuple(row) for row in df_read.values]
try:
    cursor = connection.cursor()
    batch_size = 1000
    for i in range(0, len(values), batch_size):
        batch_values = values[i:i+batch_size]
        cursor.executemany(insert_sql, batch_values)
        connection.commit()  # Commit the batch after insertion

    print("Data inserted successfully!")

except Exception as e:
    print(f"Error occurred: {e}")

Data inserted successfully!

In [43]:
connection.close()